version: "3.9"

services:
  postgres_db:
    image: "postgres:16"
    container_name: diagram_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      #      - .:/docker-entrypoint-initdb.d
      - diagrams_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - server_net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  diagrams_server:
    container_name: diagrams_server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - server_net

networks:
  server_net:
    name: server_net

volumes:
  diagrams_data:
