name: checkstyle_frontend

on:
  pull_request:
    branches: [ "main" ]
    
    name: Lint Code Base

jobs:
  eslint:
    permissions: write-all
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_TYPESCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

