name: checkstyle_frontend

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: cd frontend; npm install

      # ESLint and Prettier must be in `package.json`
      - name: Run linter
        run: cd frontend; npm run lint
